### ISSUE TITLE
Configure sending address and table name from environment variables

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn-email-service#8]

**Comment by dakota002** [comment]
@lpsinger can this be derived from the config_from_env function? Is there a specific env variable that can be used here?

**Comment by lpsinger** [comment]
Sure... `config_from_env(prefix='EMAIL_')` or something like that.

**Comment by dakota002** [comment]
I think I wasn't clear. I meant does there currently exist some way to derive it or is there an existing environment variable that I should be referencing? 

Otherwise I will just set it up to work like that, and assume the variable name to be EMAIL_SENDER

**Comment by lpsinger** [comment]
> I think I wasn't clear. I meant does there currently exist some way to derive it or is there an existing environment variable that I should be referencing?

There is not.

**Comment by lpsinger** [comment]
The table name is not yet set.
